const { validationResult } = require('express-validator');
const db = require('../database/models');

const fs = require('fs');
const path = require('path');


let galleryFilePath = path.join(__dirname, '../database/data/gallery.json');
let galleries = JSON.parse(fs.readFileSync(galleryFilePath, 'utf-8'));

const indexController = {
    index: (req, res) => {
        db.Booking.findAll()
            .then(function (bookings) {
                res.render('index', {
                    title: 'Selena & Sirom',
                    hour: '3:00 pm',
                    day_name: 'Domingo',
                    day: 14,
                    year: 2022,
                    month: 'Agosto', 
                    data_date: '2022/08/14 3:00 PM',
                    bride: 'Selena',
                    groom: 'Sirom',
                    home: 'Inicio',
                    about: 'Nosotros',
                    love_line: 'Historia',
                    the_wedding: 'La boda',
                    invite: 'Invitación',
                    location: 'Lugar',
                    testimonials: 'Código de vestuario',
                    gallery: 'Galería',
                    galleries: galleries,
                    blog: 'Blog',
                    RSVP: 'RSVP',
                    contact: 'Contacto',
                    the_groom: {
                        he: 'El novio',
                        he_is_1: 'El tecnológico · El prudente',
                        he_is_2: 'Inteligencia multifuncional, quien combina las conexiones físicas y metafísicas (el amor, la nobleza y comprensión, con el abrazo, la sonrisa y un gesto particular).',
                        he_image: "images/groom.jpg",
                        he_image_alt: 'Imagen Sirom',
                    },
                    the_bride: {
                        she: 'La novia',
                        she_is_1: 'La creativa · La guerrera',
                        she_is_2: 'Diosa griega de la luna (Selene), habitante de la luna (Selenita), quien aporta brillo a la vida, así como la luna brilla para la tierra. Nunca para de soñar, luchar y perseverar.',
                        she_image: "images/bride.jpg",
                        she_image_alt: 'Imagen Selena',
                    },
                    we_are_getting_married: '¡Nos casamos!',
                    we_are_getting_married_p: '…ahora, permanecen estas tres Virtudes: la fe, la esperanza y el amor. Pero la más excelente de ellas es el AMOR.',
                    we_are_getting_married_p_1: '1 Corintios 13:13',
                    we_are_getting_married_p_2: 'Hoy y siempre, más allá del mañana, te necesito a mi lado, siempre como mi mejor amig@, amante y por siempre alma gemela.',
                    signature: 'images/signature.png?text=Signature',
                    signature_alt: 'Firma Án & Cris',
                    our_story: {
                        title: 'Nuestra historia de amor',
                        first_kiss: 'Nuestro primer beso',
                        first_kiss_year: 2020,
                        first_kiss_date: '24 de febrero',
                        first_kiss_p: 'Debemos congelar el tiempo, ese tiempo; tan eterno como perfecto. El tiempo etéreo. Una cena completa pues estábamos ahí, sólo eso bastaba. 10 minutos de descanso, juntos, en un mismo espacio. Era ahí donde debía ocurrir, no antes, no después. Dix minutes qui changent tout.',
                        first_kiss_image1: 'images/time-line/timeline-first-date.jpg',
                        first_kiss_alt1: 'First date',
                        first_kiss_image2: 'images/time-line/timeline-first-kiss.jpg',
                        first_kiss_alt2: 'First kiss',
                        memorable_moments: 'Algunos de nuestros momentos memorables',
                        memorable_moments_year: 2020,
                        memorable_moments_p: 'Recorremos el mundo sin límites, en el camino pisando huellas, dejando huellas.',
                        memorable_moments_slider1: 'images/time-line/timeline-slider-img1.jpg',
                        memorable_moments_alt1: 'Nuestras vacaciones - Gigante, Huila',
                        memorable_moments_slider2: 'images/time-line/timeline-slider-img2.jpg',
                        memorable_moments_alt2: 'Celebrando un mes más juntos',
                        memorable_moments_slider3: 'images/time-line/timeline-slider-img3.jpg',
                        memorable_moments_alt3: 'Nuestras vacaciones - Cúcuta, Norte de Santander',
                        memorable_moments_slider4: 'images/time-line/timeline-slider-img4.jpg',
                        memorable_moments_alt4: 'Parapente - Guasca, Cundinamarca',
                        memorable_moments_slider5: 'images/time-line/timeline-slider-img5.jpg',
                        memorable_moments_alt5: 'Nuestras vacaciones - Cartagena, Bolívar',
                        memorable_moments_slider6: 'images/time-line/timeline-slider-img6.jpg',
                        memorable_moments_alt6: 'Cumpleaños de Sirom',
                        she_said_yes: 'Ella dijo ¡Sí!',
                        she_said_yes_year: 2021,
                        she_said_yes_date: '28 de febrero',
                        she_said_yes_p: 'Siendo nuestro aniversario, salimos a caminar a la montaña, la vista era mágica. Regresamos al glamping, a lo lejos se veía un árbol de madera, pétalos de rosa y alguna decoración que envolvía el momento con incógnitas, nervios, ansiedad y emoción.',
                        she_said_yes_image1: 'images/time-line/timeline-proposal-img1.jpg',
                        she_said_yes_alt1: '',
                        she_said_yes_image2: 'images/time-line/timeline-proposal-img2.jpg',
                        she_said_yes_alt2: '',
                        she_said_yes_text1: '¡Aquí es donde nuestro',
                        she_said_yes_text2: 'Por siempre',
                        she_said_yes_text3: 'Comienza!'  
                    },
                    invitation: {
                        title: 'Tenemos el honor de invitarte a nuestra boda',
                        location_1: 'Hotel Santorini, Casa de Playa Piedra Incada N° 3',
                        location_2: 'Santa Marta, Colombia',
                    },
                    location_details: {
                        ceremony: 'Ceremonia',
                        ceremony_hour: '4:00 pm',
                        photobooth: 'Photo Booth',
                        photobooth_hour: '5:40 pm - 7:40 pm',
                        reception: 'Recepción',
                        reception_hour: '7:00 pm',
                    },
                    outfit: {
                        title: 'Código de vestuario',
                        outfit_p: 'INFORMAL: Los tonos serán únicamente marfil / beige o blanco, telas ligeras, suaves y sencillas. Las mujeres podrán usar vestido largo, medio o corto, short, pantalón, blusas o enterizos. Los hombres podrán usar pantalones o bermudas (aplican para color caqui), camisa a su gusto siempre y cuando mantenga los colores permitidos. Los estampados y colores llamativos NO están permitidos. Calzado según gusto y comodidad.',
                        for_her: 'Para ellas',
                        for_him: 'Para ellos',
                        for_her_img1 : './images/outfit/outfit_her_1.jpg',
                        for_her_img2 : './images/outfit/outfit_her_2.jpg',
                        for_her_img3 : './images/outfit/outfit_her_3.jpg',
                        for_him_img1 : './images/outfit/outfit_him_1.jpg',
                        for_him_img2 : './images/outfit/outfit_him_2.jpg',
                        for_him_img3 : './images/outfit/outfit_him_3.jpg',
                    },
                    reservation: {
                        title: 'Confírmanos tu asistencia',
                        reservation_p: 'Test',
                        name: 'Tu nombre*',
                        email: 'Correo electrónico*',
                        phone: 'Teléfono*',
                        guests: 'Numero de invitados',
                        preferences: 'Preferencia de bebida',
                        water: 'Agua',
                        soda: 'Gaseosa',
                        whiskey: 'Whisky',
                        wine: 'Vino',
                        beer: 'Cerveza',
                        message: 'Déjanos un mensaje',
                        rsvp_si: 'Sí, asistiré.',
                        rsvp_no: 'Lo siento, no puedo ir.',
                        submit: 'Enviar',
                    }
                });
            })
            .catch((error) => console.log(error));
    },
    createBooking: async (req, res) => {
        let errors = validationResult(req);
        let emailUser = await db.Guest.findAll({
            where: {
                [db.Sequelize.Op.or]: [
                    {email: req.body.email}, 
                    {phone: req.body.phone}
                ]
            }
        });
        if (!errors.isEmpty()) {
            return res.render('index',{
                title: 'Selena & Sirom',
                hour: '3:00 pm',
                day_name: 'Domingo',
                day: 14,
                year: 2022,
                month: 'Agosto', 
                data_date: '2022/08/14 3:00 PM',
                bride: 'Selena',
                groom: 'Sirom',
                home: 'Inicio',
                about: 'Nosotros',
                love_line: 'Historia',
                the_wedding: 'La boda',
                invite: 'Invitación',
                location: 'Lugar',
                testimonials: 'Código de vestuario',
                gallery: 'Galería',
                galleries: galleries,
                blog: 'Blog',
                RSVP: 'RSVP',
                contact: 'Contacto',
                the_groom: {
                    he: 'El novio',
                    he_is_1: 'El tecnológico · El prudente',
                    he_is_2: 'Inteligencia multifuncional, quien combina las conexiones físicas y metafísicas (el amor, la nobleza y comprensión, con el abrazo, la sonrisa y un gesto particular).',
                    he_image: "images/groom.jpg",
                    he_image_alt: 'Imagen Sirom',
                },
                    the_bride: {
                    she: 'La novia',
                    she_is_1: 'La creativa · La guerrera',
                    she_is_2: 'Diosa griega de la luna (Selene), habitante de la luna (Selenita), quien aporta brillo a la vida, así como la luna brilla para la tierra. Nunca para de soñar, luchar y perseverar.',
                    she_image: "images/bride.jpg",
                    she_image_alt: 'Imagen Selena',
                },
                we_are_getting_married: '¡Nos casamos!',
                we_are_getting_married_p: '…ahora, permanecen estas tres Virtudes: la fe, la esperanza y el amor. Pero la más excelente de ellas es el AMOR.',
                we_are_getting_married_p_1: '1 Corintios 13:13',
                we_are_getting_married_p_2: 'Hoy y siempre, más allá del mañana, te necesito a mi lado, siempre como mi mejor amig@, amante y por siempre alma gemela.',
                signature: 'images/signature.png?text=Signature',
                signature_alt: 'Firma Án & Cris',
                our_story: {
                    title: 'Nuestra historia de amor',
                    first_kiss: 'Nuestro primer beso',
                    first_kiss_year: 2020,
                    first_kiss_date: '24 de febrero',
                    first_kiss_p: 'Debemos congelar el tiempo, ese tiempo; tan eterno como perfecto. El tiempo etéreo. Una cena completa pues estábamos ahí, sólo eso bastaba. 10 minutos de descanso, juntos, en un mismo espacio. Era ahí donde debía ocurrir, no antes, no después. Dix minutes qui changent tout.',
                    first_kiss_image1: 'images/time-line/timeline-first-date.jpg',
                    first_kiss_alt1: 'First date',
                    first_kiss_image2: 'images/time-line/timeline-first-kiss.jpg',
                    first_kiss_alt2: 'First kiss',
                    memorable_moments: 'Algunos de nuestros momentos memorables',
                    memorable_moments_year: 2020,
                    memorable_moments_p: 'Recorremos el mundo sin límites, en el camino pisando huellas, dejando huellas.',
                    memorable_moments_slider1: 'images/time-line/timeline-slider-img1.jpg',
                    memorable_moments_alt1: 'Nuestras vacaciones - Gigante, Huila',
                    memorable_moments_slider2: 'images/time-line/timeline-slider-img2.jpg',
                    memorable_moments_alt2: 'Celebrando un mes más juntos',
                    memorable_moments_slider3: 'images/time-line/timeline-slider-img3.jpg',
                    memorable_moments_alt3: 'Nuestras vacaciones - Cúcuta, Norte de Santander',
                    memorable_moments_slider4: 'images/time-line/timeline-slider-img4.jpg',
                    memorable_moments_alt4: 'Parapente - Guasca, Cundinamarca',
                    memorable_moments_slider5: 'images/time-line/timeline-slider-img5.jpg',
                    memorable_moments_alt5: 'Nuestras vacaciones - Cartagena, Bolívar',
                    memorable_moments_slider6: 'images/time-line/timeline-slider-img6.jpg',
                    memorable_moments_alt6: 'Cumpleaños de Sirom',
                    she_said_yes: 'Ella dijo ¡Sí!',
                    she_said_yes_year: 2021,
                    she_said_yes_date: '28 de febrero',
                    she_said_yes_p: 'Siendo nuestro aniversario, salimos a caminar a la montaña, la vista era mágica. Regresamos al glamping, a lo lejos se veía un árbol de madera, pétalos de rosa y alguna decoración que envolvía el momento con incógnitas, nervios, ansiedad y emoción.',
                    she_said_yes_image1: 'images/time-line/timeline-proposal-img1.jpg',
                    she_said_yes_alt1: '',
                    she_said_yes_image2: 'images/time-line/timeline-proposal-img2.jpg',
                    she_said_yes_alt2: '',
                    she_said_yes_text1: '¡Aquí es donde nuestro',
                    she_said_yes_text2: 'Por siempre',
                    she_said_yes_text3: 'Comienza!'  
                },
                    invitation: {
                    title: 'Tenemos el honor de invitarte a nuestra boda',
                    location_1: 'Hotel Santorini, Casa de Playa Piedra Incada N° 3',
                    location_2: 'Santa Marta, Colombia',
                },
                    location_details: {
                    ceremony: 'Ceremonia',
                    ceremony_hour: '4:00 pm',
                    photobooth: 'Photo Booth',
                    photobooth_hour: '5:40 pm - 7:40 pm',
                    reception: 'Recepción',
                    reception_hour: '7:00 pm',
                },
                    outfit: {
                    title: 'Código de vestuario',
                    outfit_p: 'INFORMAL: Los tonos serán únicamente marfil / beige o blanco, telas ligeras, suaves y sencillas. Las mujeres podrán usar vestido largo, medio o corto, short, pantalón, blusas o enterizos. Los hombres podrán usar pantalones o bermudas (aplican para color caqui), camisa a su gusto siempre y cuando mantenga los colores permitidos. Los estampados y colores llamativos NO están permitidos. Calzado según gusto y comodidad.',
                    for_her: 'Para ellas',
                    for_him: 'Para ellos',
                    for_her_img1 : './images/outfit/outfit_her_1.jpg',
                    for_her_img2 : './images/outfit/outfit_her_2.jpg',
                    for_her_img3 : './images/outfit/outfit_her_3.jpg',
                    for_him_img1 : './images/outfit/outfit_him_1.jpg',
                    for_him_img2 : './images/outfit/outfit_him_2.jpg',
                    for_him_img3 : './images/outfit/outfit_him_3.jpg',
                },
                reservation: {
                    title: 'Confírmanos tu asistencia',
                    reservation_p: 'Test',
                    name: 'Tu nombre*',
                    email: 'Correo electrónico*',
                    phone: 'Teléfono*',
                    guests: 'Numero de invitados',
                    preferences: 'Preferencia de bebida',
                    water: 'Agua',
                    soda: 'Gaseosa',
                    whiskey: 'Whisky',
                    wine: 'Vino',
                    beer: 'Cerveza',
                    message: 'Déjanos un mensaje',
                    rsvp_si: 'Sí, asistiré.',
                    rsvp_no: 'Lo siento, no puedo ir.',
                    submit: 'Enviar',
                },
                oldData: req.body,
                errors: errors.array()
            });
        } else if (emailUser.length > 0) {
            let emailBooking = await db.Booking.findAll({
                where: {
                  email: req.body.email
                }
            });
            if (emailBooking.length > 0) {
                res.render('index', {
                    title: 'Selena & Sirom',
                    hour: '3:00 pm',
                    day_name: 'Domingo',
                    day: 14,
                    year: 2022,
                    month: 'Agosto', 
                    data_date: '2022/08/14 3:00 PM',
                    bride: 'Selena',
                    groom: 'Sirom',
                    home: 'Inicio',
                    about: 'Nosotros',
                    love_line: 'Historia',
                    the_wedding: 'La boda',
                    invite: 'Invitación',
                    location: 'Lugar',
                    testimonials: 'Código de vestuario',
                    gallery: 'Galería',
                    galleries: galleries,
                    blog: 'Blog',
                    RSVP: 'RSVP',
                    contact: 'Contacto',
                    the_groom: {
                        he: 'El novio',
                        he_is_1: 'El tecnológico · El prudente',
                        he_is_2: 'Inteligencia multifuncional, quien combina las conexiones físicas y metafísicas (el amor, la nobleza y comprensión, con el abrazo, la sonrisa y un gesto particular).',
                        he_image: "images/groom.jpg",
                        he_image_alt: 'Imagen Sirom',
                    },
                        the_bride: {
                        she: 'La novia',
                        she_is_1: 'La creativa · La guerrera',
                        she_is_2: 'Diosa griega de la luna (Selene), habitante de la luna (Selenita), quien aporta brillo a la vida, así como la luna brilla para la tierra. Nunca para de soñar, luchar y perseverar.',
                        she_image: "images/bride.jpg",
                        she_image_alt: 'Imagen Selena',
                    },
                    we_are_getting_married: '¡Nos casamos!',
                    we_are_getting_married_p: '…ahora, permanecen estas tres Virtudes: la fe, la esperanza y el amor. Pero la más excelente de ellas es el AMOR.',
                    we_are_getting_married_p_1: '1 Corintios 13:13',
                    we_are_getting_married_p_2: 'Hoy y siempre, más allá del mañana, te necesito a mi lado, siempre como mi mejor amig@, amante y por siempre alma gemela.',
                    signature: 'images/signature.png?text=Signature',
                    signature_alt: 'Firma Án & Cris',
                    our_story: {
                        title: 'Nuestra historia de amor',
                        first_kiss: 'Nuestro primer beso',
                        first_kiss_year: 2020,
                        first_kiss_date: '24 de febrero',
                        first_kiss_p: 'Debemos congelar el tiempo, ese tiempo; tan eterno como perfecto. El tiempo etéreo. Una cena completa pues estábamos ahí, sólo eso bastaba. 10 minutos de descanso, juntos, en un mismo espacio. Era ahí donde debía ocurrir, no antes, no después. Dix minutes qui changent tout.',
                        first_kiss_image1: 'images/time-line/timeline-first-date.jpg',
                        first_kiss_alt1: 'First date',
                        first_kiss_image2: 'images/time-line/timeline-first-kiss.jpg',
                        first_kiss_alt2: 'First kiss',
                        memorable_moments: 'Algunos de nuestros momentos memorables',
                        memorable_moments_year: 2020,
                        memorable_moments_p: 'Recorremos el mundo sin límites, en el camino pisando huellas, dejando huellas.',
                        memorable_moments_slider1: 'images/time-line/timeline-slider-img1.jpg',
                        memorable_moments_alt1: 'Nuestras vacaciones - Gigante, Huila',
                        memorable_moments_slider2: 'images/time-line/timeline-slider-img2.jpg',
                        memorable_moments_alt2: 'Celebrando un mes más juntos',
                        memorable_moments_slider3: 'images/time-line/timeline-slider-img3.jpg',
                        memorable_moments_alt3: 'Nuestras vacaciones - Cúcuta, Norte de Santander',
                        memorable_moments_slider4: 'images/time-line/timeline-slider-img4.jpg',
                        memorable_moments_alt4: 'Parapente - Guasca, Cundinamarca',
                        memorable_moments_slider5: 'images/time-line/timeline-slider-img5.jpg',
                        memorable_moments_alt5: 'Nuestras vacaciones - Cartagena, Bolívar',
                        memorable_moments_slider6: 'images/time-line/timeline-slider-img6.jpg',
                        memorable_moments_alt6: 'Cumpleaños de Sirom',
                        she_said_yes: 'Ella dijo ¡Sí!',
                        she_said_yes_year: 2021,
                        she_said_yes_date: '28 de febrero',
                        she_said_yes_p: 'Siendo nuestro aniversario, salimos a caminar a la montaña, la vista era mágica. Regresamos al glamping, a lo lejos se veía un árbol de madera, pétalos de rosa y alguna decoración que envolvía el momento con incógnitas, nervios, ansiedad y emoción.',
                        she_said_yes_image1: 'images/time-line/timeline-proposal-img1.jpg',
                        she_said_yes_alt1: '',
                        she_said_yes_image2: 'images/time-line/timeline-proposal-img2.jpg',
                        she_said_yes_alt2: '',
                        she_said_yes_text1: '¡Aquí es donde nuestro',
                        she_said_yes_text2: 'Por siempre',
                        she_said_yes_text3: 'Comienza!'  
                    },
                        invitation: {
                        title: 'Tenemos el honor de invitarte a nuestra boda',
                        location_1: 'Hotel Santorini, Casa de Playa Piedra Incada N° 3',
                        location_2: 'Santa Marta, Colombia',
                    },
                        location_details: {
                        ceremony: 'Ceremonia',
                        ceremony_hour: '4:00 pm',
                        photobooth: 'Photo Booth',
                        photobooth_hour: '5:40 pm - 7:40 pm',
                        reception: 'Recepción',
                        reception_hour: '7:00 pm',
                    },
                        outfit: {
                        title: 'Código de vestuario',
                        outfit_p: 'INFORMAL: Los tonos serán únicamente marfil / beige o blanco, telas ligeras, suaves y sencillas. Las mujeres podrán usar vestido largo, medio o corto, short, pantalón, blusas o enterizos. Los hombres podrán usar pantalones o bermudas (aplican para color caqui), camisa a su gusto siempre y cuando mantenga los colores permitidos. Los estampados y colores llamativos NO están permitidos. Calzado según gusto y comodidad.',
                        for_her: 'Para ellas',
                        for_him: 'Para ellos',
                        for_her_img1 : './images/outfit/outfit_her_1.jpg',
                        for_her_img2 : './images/outfit/outfit_her_2.jpg',
                        for_her_img3 : './images/outfit/outfit_her_3.jpg',
                        for_him_img1 : './images/outfit/outfit_him_1.jpg',
                        for_him_img2 : './images/outfit/outfit_him_2.jpg',
                        for_him_img3 : './images/outfit/outfit_him_3.jpg',
                    },
                    reservation: {
                        title: 'Confírmanos tu asistencia',
                        reservation_p: 'Test',
                        name: 'Tu nombre*',
                        email: 'Correo electrónico*',
                        phone: 'Teléfono*',
                        guests: 'Numero de invitados',
                        preferences: 'Preferencia de bebida',
                        water: 'Agua',
                        soda: 'Gaseosa',
                        whiskey: 'Whisky',
                        wine: 'Vino',
                        beer: 'Cerveza',
                        message: 'Déjanos un mensaje',
                        rsvp_si: 'Sí, asistiré.',
                        rsvp_no: 'Lo siento, no puedo ir.',
                        submit: 'Enviar',
                    },
                    oldData: req.body,     
                    errors: [
                        { msg: 'Ya te encuentras registrado.' },
                        { msg: 'Gracias de nuevo por confirmar. S&S' },]
                });
            } else {
                db.Booking.create({
                    Name: req.body.name,
                    Email: req.body.email,
                    Phone: req.body.phone,
                    Confirmation: req.body.confirmation,
                    Guests: req.body.guests,
                    Water: req.body.water,
                    Soda: req.body.soda,
                    Whiskey: req.body.whiskey,
                    Wine: req.body.wine,
                    Beer: req.body.beer,
                    Message: req.body.message,
                })
                    .then(() => {
                        return res.render('index',{
                            title: 'Selena & Sirom',
                            hour: '3:00 pm',
                            day_name: 'Domingo',
                            day: 14,
                            year: 2022,
                            month: 'Agosto', 
                            data_date: '2022/08/14 3:00 PM',
                            bride: 'Selena',
                            groom: 'Sirom',
                            home: 'Inicio',
                            about: 'Nosotros',
                            love_line: 'Historia',
                            the_wedding: 'La boda',
                            invite: 'Invitación',
                            location: 'Lugar',
                            testimonials: 'Código de vestuario',
                            gallery: 'Galería',
                            galleries: galleries,
                            blog: 'Blog',
                            RSVP: 'RSVP',
                            contact: 'Contacto',
                            the_groom: {
                                he: 'El novio',
                                he_is_1: 'El tecnológico · El prudente',
                                he_is_2: 'Inteligencia multifuncional, quien combina las conexiones físicas y metafísicas (el amor, la nobleza y comprensión, con el abrazo, la sonrisa y un gesto particular).',
                                he_image: "images/groom.jpg",
                                he_image_alt: 'Imagen Sirom',
                            },
                                the_bride: {
                                she: 'La novia',
                                she_is_1: 'La creativa · La guerrera',
                                she_is_2: 'Diosa griega de la luna (Selene), habitante de la luna (Selenita), quien aporta brillo a la vida, así como la luna brilla para la tierra. Nunca para de soñar, luchar y perseverar.',
                                she_image: "images/bride.jpg",
                                she_image_alt: 'Imagen Selena',
                            },
                            we_are_getting_married: '¡Nos casamos!',
                            we_are_getting_married_p: '…ahora, permanecen estas tres Virtudes: la fe, la esperanza y el amor. Pero la más excelente de ellas es el AMOR.',
                            we_are_getting_married_p_1: '1 Corintios 13:13',
                            we_are_getting_married_p_2: 'Hoy y siempre, más allá del mañana, te necesito a mi lado, siempre como mi mejor amig@, amante y por siempre alma gemela.',
                            signature: 'images/signature.png?text=Signature',
                            signature_alt: 'Firma Án & Cris',
                            our_story: {
                                title: 'Nuestra historia de amor',
                                first_kiss: 'Nuestro primer beso',
                                first_kiss_year: 2020,
                                first_kiss_date: '24 de febrero',
                                first_kiss_p: 'Debemos congelar el tiempo, ese tiempo; tan eterno como perfecto. El tiempo etéreo. Una cena completa pues estábamos ahí, sólo eso bastaba. 10 minutos de descanso, juntos, en un mismo espacio. Era ahí donde debía ocurrir, no antes, no después. Dix minutes qui changent tout.',
                                first_kiss_image1: 'images/time-line/timeline-first-date.jpg',
                                first_kiss_alt1: 'First date',
                                first_kiss_image2: 'images/time-line/timeline-first-kiss.jpg',
                                first_kiss_alt2: 'First kiss',
                                memorable_moments: 'Algunos de nuestros momentos memorables',
                                memorable_moments_year: 2020,
                                memorable_moments_p: 'Recorremos el mundo sin límites, en el camino pisando huellas, dejando huellas.',
                                memorable_moments_slider1: 'images/time-line/timeline-slider-img1.jpg',
                                memorable_moments_alt1: 'Nuestras vacaciones - Gigante, Huila',
                                memorable_moments_slider2: 'images/time-line/timeline-slider-img2.jpg',
                                memorable_moments_alt2: 'Celebrando un mes más juntos',
                                memorable_moments_slider3: 'images/time-line/timeline-slider-img3.jpg',
                                memorable_moments_alt3: 'Nuestras vacaciones - Cúcuta, Norte de Santander',
                                memorable_moments_slider4: 'images/time-line/timeline-slider-img4.jpg',
                                memorable_moments_alt4: 'Parapente - Guasca, Cundinamarca',
                                memorable_moments_slider5: 'images/time-line/timeline-slider-img5.jpg',
                                memorable_moments_alt5: 'Nuestras vacaciones - Cartagena, Bolívar',
                                memorable_moments_slider6: 'images/time-line/timeline-slider-img6.jpg',
                                memorable_moments_alt6: 'Cumpleaños de Sirom',
                                she_said_yes: 'Ella dijo ¡Sí!',
                                she_said_yes_year: 2021,
                                she_said_yes_date: '28 de febrero',
                                she_said_yes_p: 'Siendo nuestro aniversario, salimos a caminar a la montaña, la vista era mágica. Regresamos al glamping, a lo lejos se veía un árbol de madera, pétalos de rosa y alguna decoración que envolvía el momento con incógnitas, nervios, ansiedad y emoción.',
                                she_said_yes_image1: 'images/time-line/timeline-proposal-img1.jpg',
                                she_said_yes_alt1: '',
                                she_said_yes_image2: 'images/time-line/timeline-proposal-img2.jpg',
                                she_said_yes_alt2: '',
                                she_said_yes_text1: '¡Aquí es donde nuestro',
                                she_said_yes_text2: 'Por siempre',
                                she_said_yes_text3: 'Comienza!'  
                            },
                                invitation: {
                                title: 'Tenemos el honor de invitarte a nuestra boda',
                                location_1: 'Hotel Santorini, Casa de Playa Piedra Incada N° 3',
                                location_2: 'Santa Marta, Colombia',
                            },
                                location_details: {
                                ceremony: 'Ceremonia',
                                ceremony_hour: '4:00 pm',
                                photobooth: 'Photo Booth',
                                photobooth_hour: '5:40 pm - 7:40 pm',
                                reception: 'Recepción',
                                reception_hour: '7:00 pm',
                            },
                                outfit: {
                                title: 'Código de vestuario',
                                outfit_p: 'INFORMAL: Los tonos serán únicamente marfil / beige o blanco, telas ligeras, suaves y sencillas. Las mujeres podrán usar vestido largo, medio o corto, short, pantalón, blusas o enterizos. Los hombres podrán usar pantalones o bermudas (aplican para color caqui), camisa a su gusto siempre y cuando mantenga los colores permitidos. Los estampados y colores llamativos NO están permitidos. Calzado según gusto y comodidad.',
                                for_her: 'Para ellas',
                                for_him: 'Para ellos',
                                for_her_img1 : './images/outfit/outfit_her_1.jpg',
                                for_her_img2 : './images/outfit/outfit_her_2.jpg',
                                for_her_img3 : './images/outfit/outfit_her_3.jpg',
                                for_him_img1 : './images/outfit/outfit_him_1.jpg',
                                for_him_img2 : './images/outfit/outfit_him_2.jpg',
                                for_him_img3 : './images/outfit/outfit_him_3.jpg',
                            },
                            reservation: {
                                title: 'Confírmanos tu asistencia',
                                reservation_p: 'Test',
                                name: 'Tu nombre*',
                                email: 'Correo electrónico*',
                                phone: 'Teléfono*',
                                guests: 'Numero de invitados',
                                preferences: 'Preferencia de bebida',
                                water: 'Agua',
                                soda: 'Gaseosa',
                                whiskey: 'Whisky',
                                wine: 'Vino',
                                beer: 'Cerveza',
                                message: 'Déjanos un mensaje',
                                rsvp_si: 'Sí, asistiré.',
                                rsvp_no: 'Lo siento, no puedo ir.',
                                submit: 'Enviar',
                            },
                            success: 'Gracias por confirmar, te esperamos. S&S'
                        });
                    }).catch((error) => console.log(error));    
                }
        } else {
            res.render('index', {
                title: 'Selena & Sirom',
                hour: '3:00 pm',
                day_name: 'Domingo',
                day: 14,
                year: 2022,
                month: 'Agosto', 
                data_date: '2022/08/14 3:00 PM',
                bride: 'Selena',
                groom: 'Sirom',
                home: 'Inicio',
                about: 'Nosotros',
                love_line: 'Historia',
                the_wedding: 'La boda',
                invite: 'Invitación',
                location: 'Lugar',
                testimonials: 'Código de vestuario',
                gallery: 'Galería',
                galleries: galleries,
                blog: 'Blog',
                RSVP: 'RSVP',
                contact: 'Contacto',
                the_groom: {
                    he: 'El novio',
                    he_is_1: 'El tecnológico · El prudente',
                    he_is_2: 'Inteligencia multifuncional, quien combina las conexiones físicas y metafísicas (el amor, la nobleza y comprensión, con el abrazo, la sonrisa y un gesto particular).',
                    he_image: "images/groom.jpg",
                    he_image_alt: 'Imagen Sirom',
                },
                    the_bride: {
                    she: 'La novia',
                    she_is_1: 'La creativa · La guerrera',
                    she_is_2: 'Diosa griega de la luna (Selene), habitante de la luna (Selenita), quien aporta brillo a la vida, así como la luna brilla para la tierra. Nunca para de soñar, luchar y perseverar.',
                    she_image: "images/bride.jpg",
                    she_image_alt: 'Imagen Selena',
                },
                we_are_getting_married: '¡Nos casamos!',
                we_are_getting_married_p: '…ahora, permanecen estas tres Virtudes: la fe, la esperanza y el amor. Pero la más excelente de ellas es el AMOR.',
                we_are_getting_married_p_1: '1 Corintios 13:13',
                we_are_getting_married_p_2: 'Hoy y siempre, más allá del mañana, te necesito a mi lado, siempre como mi mejor amig@, amante y por siempre alma gemela.',
                signature: 'images/signature.png?text=Signature',
                signature_alt: 'Firma Án & Cris',
                our_story: {
                    title: 'Nuestra historia de amor',
                    first_kiss: 'Nuestro primer beso',
                    first_kiss_year: 2020,
                    first_kiss_date: '24 de febrero',
                    first_kiss_p: 'Debemos congelar el tiempo, ese tiempo; tan eterno como perfecto. El tiempo etéreo. Una cena completa pues estábamos ahí, sólo eso bastaba. 10 minutos de descanso, juntos, en un mismo espacio. Era ahí donde debía ocurrir, no antes, no después. Dix minutes qui changent tout.',
                    first_kiss_image1: 'images/time-line/timeline-first-date.jpg',
                    first_kiss_alt1: 'First date',
                    first_kiss_image2: 'images/time-line/timeline-first-kiss.jpg',
                    first_kiss_alt2: 'First kiss',
                    memorable_moments: 'Algunos de nuestros momentos memorables',
                    memorable_moments_year: 2020,
                    memorable_moments_p: 'Recorremos el mundo sin límites, en el camino pisando huellas, dejando huellas.',
                    memorable_moments_slider1: 'images/time-line/timeline-slider-img1.jpg',
                    memorable_moments_alt1: 'Nuestras vacaciones - Gigante, Huila',
                    memorable_moments_slider2: 'images/time-line/timeline-slider-img2.jpg',
                    memorable_moments_alt2: 'Celebrando un mes más juntos',
                    memorable_moments_slider3: 'images/time-line/timeline-slider-img3.jpg',
                    memorable_moments_alt3: 'Nuestras vacaciones - Cúcuta, Norte de Santander',
                    memorable_moments_slider4: 'images/time-line/timeline-slider-img4.jpg',
                    memorable_moments_alt4: 'Parapente - Guasca, Cundinamarca',
                    memorable_moments_slider5: 'images/time-line/timeline-slider-img5.jpg',
                    memorable_moments_alt5: 'Nuestras vacaciones - Cartagena, Bolívar',
                    memorable_moments_slider6: 'images/time-line/timeline-slider-img6.jpg',
                    memorable_moments_alt6: 'Cumpleaños de Sirom',
                    she_said_yes: 'Ella dijo ¡Sí!',
                    she_said_yes_year: 2021,
                    she_said_yes_date: '28 de febrero',
                    she_said_yes_p: 'Siendo nuestro aniversario, salimos a caminar a la montaña, la vista era mágica. Regresamos al glamping, a lo lejos se veía un árbol de madera, pétalos de rosa y alguna decoración que envolvía el momento con incógnitas, nervios, ansiedad y emoción.',
                    she_said_yes_image1: 'images/time-line/timeline-proposal-img1.jpg',
                    she_said_yes_alt1: '',
                    she_said_yes_image2: 'images/time-line/timeline-proposal-img2.jpg',
                    she_said_yes_alt2: '',
                    she_said_yes_text1: '¡Aquí es donde nuestro',
                    she_said_yes_text2: 'Por siempre',
                    she_said_yes_text3: 'Comienza!'  
                },
                    invitation: {
                    title: 'Tenemos el honor de invitarte a nuestra boda',
                    location_1: 'Hotel Santorini, Casa de Playa Piedra Incada N° 3',
                    location_2: 'Santa Marta, Colombia',
                },
                    location_details: {
                    ceremony: 'Ceremonia',
                    ceremony_hour: '4:00 pm',
                    photobooth: 'Photo Booth',
                    photobooth_hour: '5:40 pm - 7:40 pm',
                    reception: 'Recepción',
                    reception_hour: '7:00 pm',
                },
                    outfit: {
                    title: 'Código de vestuario',
                    outfit_p: 'INFORMAL: Los tonos serán únicamente marfil / beige o blanco, telas ligeras, suaves y sencillas. Las mujeres podrán usar vestido largo, medio o corto, short, pantalón, blusas o enterizos. Los hombres podrán usar pantalones o bermudas (aplican para color caqui), camisa a su gusto siempre y cuando mantenga los colores permitidos. Los estampados y colores llamativos NO están permitidos. Calzado según gusto y comodidad.',
                    for_her: 'Para ellas',
                    for_him: 'Para ellos',
                    for_her_img1 : './images/outfit/outfit_her_1.jpg',
                    for_her_img2 : './images/outfit/outfit_her_2.jpg',
                    for_her_img3 : './images/outfit/outfit_her_3.jpg',
                    for_him_img1 : './images/outfit/outfit_him_1.jpg',
                    for_him_img2 : './images/outfit/outfit_him_2.jpg',
                    for_him_img3 : './images/outfit/outfit_him_3.jpg',
                },
                reservation: {
                    title: 'Confírmanos tu asistencia',
                    reservation_p: 'Test',
                    name: 'Tu nombre*',
                    email: 'Correo electrónico*',
                    phone: 'Teléfono*',
                    guests: 'Numero de invitados',
                    preferences: 'Preferencia de bebida',
                    water: 'Agua',
                    soda: 'Gaseosa',
                    whiskey: 'Whisky',
                    wine: 'Vino',
                    beer: 'Cerveza',
                    message: 'Déjanos un mensaje',
                    rsvp_si: 'Sí, asistiré.',
                    rsvp_no: 'Lo siento, no puedo ir.',
                    submit: 'Enviar',
                },
                oldData: req.body,     
                errors: [
                    { msg: 'No se encuentra en la lista de invitados:' },
                    { msg: 'Por favor verifique su correo electrónico o número de teléfono.' },]
            });
        }
    }
}

module.exports = indexController;

    